sonar.projectKey=stayease-sliit-2026_stayease-payment-service
sonar.organization=stayease-sliit-2026
sonar.sources=src
sonar.exclusions=**/*.test.js,**/node_modules/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
